/*
Este um software para buscar arquivo ou conteudo dentro de arquivo de um unico diretório,
feito como exercicio da 4ª aula de topicos especiais

Desenvolvedor: Emerson Leonardo Zock Alves
SO testado: Opensuse
 */
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author emerson-opensuse
 */
public class BuscarArquivos extends javax.swing.JFrame {

    private String caminhoPasta = "";
    private Vector arquivos = new Vector();

    public BuscarArquivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtLocal = new javax.swing.JTextField();
        jbtnProcurar_Local = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtTextoProcurar = new javax.swing.JTextField();
        jbtn_ProcurarTexto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jchb_conteudo = new javax.swing.JCheckBox();
        jchb_nome = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jrbTXT = new javax.swing.JRadioButton();
        jrbLog = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtConteudo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlstArquivos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Arquivos");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setText("Local");

        jtxtLocal.setEnabled(false);
        jtxtLocal.setName("jtxtLocal"); // NOI18N

        jbtnProcurar_Local.setText("...");
        jbtnProcurar_Local.setToolTipText("");
        jbtnProcurar_Local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProcurar_LocalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel2.setText("Texto");

        jbtn_ProcurarTexto.setText("Procurar");
        jbtn_ProcurarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ProcurarTextoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));
        jPanel2.setName(""); // NOI18N

        jchb_conteudo.setText("Conteúdo");

        jchb_nome.setSelected(true);
        jchb_nome.setText("Nome do Arquivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchb_conteudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jchb_nome)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchb_conteudo)
                    .addComponent(jchb_nome))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Extenção"));

        jrbTXT.setSelected(true);
        jrbTXT.setText("txt");

        jrbLog.setText("log");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jrbTXT)
                .addGap(36, 36, 36)
                .addComponent(jrbLog)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTXT)
                    .addComponent(jrbLog))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Arquivos Encontrados"));

        jtxtConteudo.setEditable(false);
        jtxtConteudo.setColumns(20);
        jtxtConteudo.setRows(5);
        jtxtConteudo.setDisabledTextColor(new java.awt.Color(203, 203, 191));
        jScrollPane2.setViewportView(jtxtConteudo);

        jlstArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlstArquivosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jlstArquivos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTextoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_ProcurarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnProcurar_Local, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnProcurar_Local))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTextoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ProcurarTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnProcurar_LocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProcurar_LocalActionPerformed
        // TODO add your handling code here:
        caminhoPasta = pegarCaminhoJanela();
        if (!caminhoPasta.equals("")) {
            jtxtLocal.setText(caminhoPasta);
        }
    }//GEN-LAST:event_jbtnProcurar_LocalActionPerformed

    private void jbtn_ProcurarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ProcurarTextoActionPerformed
        // TODO add your handling code here:
        Procurar();
    }//GEN-LAST:event_jbtn_ProcurarTextoActionPerformed

    private void jlstArquivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlstArquivosMouseClicked
        // TODO add your handling code here:
        verConteudo();
    }//GEN-LAST:event_jlstArquivosMouseClicked

    public void Procurar() {
        if (!caminhoPasta.equals("")) {
            
               //limpa o vetor e a lista
             jlstArquivos.setModel(new DefaultListModel());
             jtxtConteudo.setText("");
             arquivos.clear();
             //Aqui é verificado se vai pesquisar txt ou log
            if (jrbTXT.isSelected() && !jrbLog.isSelected()) {

                //aqui pega todos os arquivos txt para o vetor arquivos
                filtroExtencao(".txt");
                //aqui filtra para mostrar os arquivos por conteudo ou pelo nome
                filtroConsultar();
            } else if (!jrbTXT.isSelected() && jrbLog.isSelected()) {
                
                filtroExtencao(".log");
                filtroConsultar();
            } else if (jrbTXT.isSelected() && jrbLog.isSelected()) {
                
                filtroExtencao(".txt");
                filtroConsultar();
                filtroExtencao(".log");
                filtroConsultar();
            } else if (!jrbTXT.isSelected() && !jrbLog.isSelected()) {
                JOptionPane.showMessageDialog(null, "Selecione uma extenção", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Local Inválido", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }

    public void filtroConsultar() {
        if (!jtxtTextoProcurar.getText().equals("")) {

            //verifica se é pelo nome ou pelo conteudo
            if (jchb_nome.isSelected() && !jchb_conteudo.isSelected()) {
                for (int i = arquivos.size()-1; i >= 0; i--) {
                    if (!arquivos.elementAt(i).toString().contains(jtxtTextoProcurar.getText())) {
                        arquivos.remove(i);
                    }
                }
                jlstArquivos.setListData(arquivos);
            }else if(!jchb_nome.isSelected() && jchb_conteudo.isSelected())
            {
                   for (int i = arquivos.size()-1; i >= 0; i--) {
                    if (!lerArquivo(caminhoPasta + "/" + arquivos.elementAt(i)).contains(jtxtTextoProcurar.getText())) {
                        arquivos.remove(i);
                    }
                }
                   jlstArquivos.setListData(arquivos);
            }else if(jchb_nome.isSelected() && jchb_conteudo.isSelected())
            {
                   for (int i = arquivos.size()-1; i >= 0; i--) {
                    if (!lerArquivo(caminhoPasta + "/" + arquivos.elementAt(i)).contains(jtxtTextoProcurar.getText()) && !arquivos.elementAt(i).toString().contains(jtxtTextoProcurar.getText())) {
                        arquivos.remove(i);
                    }
                }
                   jlstArquivos.setListData(arquivos);
            }else if(!jchb_nome.isSelected() && !jchb_conteudo.isSelected())
            {
                JOptionPane.showMessageDialog(null, "Selecione algum tipo de consulta", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
            
            if(arquivos.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Nada encontrado", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um texto para pesquisar", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }

    public void filtroExtencao(String extencao) {
        File[] files = new File(caminhoPasta).listFiles(new FilenameFilter() {
            public boolean accept(File dir, String name) {
                if (name.endsWith(extencao)) {
                    arquivos.add(name);

                    return true;
                } else {
                    return false;
                }
            }
        });
        
        if(arquivos.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Nada encontrado", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    public String pegarCaminhoJanela() {
        JFileChooser fc = new JFileChooser();
        //Define que apenar diretórios podem ser selecionados
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //Exibe o diálogo. Deve ser passado por parâmetro o JFrame de origem.
        fc.showOpenDialog(this);
        //Captura o objeto File que representa o diretório selecionado.
        File selFile = fc.getSelectedFile();
        //Mostra o caminho do diretório
        return selFile.getAbsolutePath();

    }

    public void verConteudo() {
        String conteudo = "";
        conteudo = lerArquivo(caminhoPasta + "/" + jlstArquivos.getSelectedValue());
        if(!conteudo.equals(""))
        {
            jtxtConteudo.setText(conteudo);
        }
    }

    private String lerArquivo(String nomeArquivo) {
        FileReader fileReader = null;
        BufferedReader bufferedReader = null;
        try {
            fileReader = new FileReader(nomeArquivo);
            bufferedReader = new BufferedReader(fileReader);
            StringBuilder sb = new StringBuilder();
            while (bufferedReader.ready()) {
                sb.append(bufferedReader.readLine());
                sb.append("\n");
            }
            return sb.toString();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir o arquivo: "
                    + ex.getMessage());
        } finally {
            if (bufferedReader != null) {
                try {
                    bufferedReader.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao abrir o arquivo: "
                            + ex.getMessage());
                }
            }
            if (fileReader != null) {
                try {
                    fileReader.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao abrir o arquivo: "
                            + ex.getMessage());
                }
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarArquivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarArquivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarArquivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarArquivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarArquivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnProcurar_Local;
    private javax.swing.JButton jbtn_ProcurarTexto;
    private javax.swing.JCheckBox jchb_conteudo;
    private javax.swing.JCheckBox jchb_nome;
    private javax.swing.JList<String> jlstArquivos;
    private javax.swing.JRadioButton jrbLog;
    private javax.swing.JRadioButton jrbTXT;
    private javax.swing.JTextArea jtxtConteudo;
    private javax.swing.JTextField jtxtLocal;
    private javax.swing.JTextField jtxtTextoProcurar;
    // End of variables declaration//GEN-END:variables
}
